
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.*;
import java.awt.event.*;
import java.util.Base64;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author trank
 */
public class NewJFrame extends javax.swing.JFrame {
      private int n = 256;
      private byte[] S = new byte[256];
      private int x = 0;
      private int y = 0;
      private SecretKey secretKey;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jPanelA5.setVisible(false);
        jPanelRC4.setVisible(false);
        jPanelHome.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //RC4
   
    
   

    // Constructor for RC4
    public NewJFrame(String key) {
        key_init(key.getBytes());
    }

    // Initialize key for RC4
    private void key_init(byte[] key) {
        int key_length = key.length;
        int j = 0;

        for (int i = 0; i < n; i++) {
            S[i] = (byte) i;
        }

        for (int i = 0; i < n; i++) {
            j = (j + S[i] + key[i % key_length]) & 0xFF;
            swap(i, j);
        }
    }

    private byte ask_number() {
        x = (x + 1) & 0xFF;
        y = (y + S[x]) & 0xFF;
        swap(x, y);
        return S[(S[x] + S[y]) & 0xFF];
    }

    public String encryptRC4(String input) {
        byte[] inputBytes = input.getBytes();
        byte[] result = new byte[inputBytes.length];

        for (int i = 0; i < inputBytes.length; i++) {
            result[i] = (byte) (inputBytes[i] ^ ask_number());
        }

        StringBuilder hexResult = new StringBuilder();
        for (byte b : result) {
            hexResult.append(String.format("%02x", b));
        }

        return hexResult.toString();
    }

    public String decryptRC4(String Hexinput) {
        byte[] HexinputBytes = new byte[Hexinput.length() / 2];

        for (int i = 0; i < Hexinput.length(); i += 2) {
            HexinputBytes[i / 2] = (byte) Integer.parseInt(Hexinput.substring(i, i + 2), 16);
        }

        StringBuilder plaintext = new StringBuilder();
        for (byte b : HexinputBytes) {
            byte decryptByte = (byte) (b ^ ask_number());
            plaintext.append((char) decryptByte);
        }

        return plaintext.toString();
    }

    private void swap(int a, int b) {
        byte temp = S[a];
        S[a] = S[b];
        S[b] = temp;
    }
    
    
   
    
    //A5
     private SecretKey generateSecretKey() {
        try {
            KeyGenerator keyGen = KeyGenerator.getInstance("AES");
            keyGen.init(256);
            return keyGen.generateKey();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate secret key", e);
        }
    }
      private String encrypt(String plainText, SecretKey key) throws Exception {
        Cipher cipher = Cipher.getInstance("AES");
        cipher.init(Cipher.ENCRYPT_MODE, key);
        byte[] encryptedBytes = cipher.doFinal(plainText.getBytes());
        return Base64.getEncoder().encodeToString(encryptedBytes);
    }

    private String decrypt(String encryptedText, SecretKey key) throws Exception {
        Cipher cipher = Cipher.getInstance("AES");
        cipher.init(Cipher.DECRYPT_MODE, key);
        byte[] decodedBytes = Base64.getDecoder().decode(encryptedText);
        byte[] decryptedBytes = cipher.doFinal(decodedBytes);
        return new String(decryptedBytes);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        Jpanel_Menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jpanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JpanelMain = new javax.swing.JPanel();
        jPanelA5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnKeyGenaration = new javax.swing.JButton();
        ENCRYPTA5 = new javax.swing.JButton();
        txtTextA5 = new javax.swing.JTextField();
        txtResultA5 = new javax.swing.JTextField();
        btnDECRYPTA5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKeyA5 = new javax.swing.JTextArea();
        jPanelRC4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnECRYPTRC4 = new javax.swing.JButton();
        btnDECRYPTRC4 = new javax.swing.JButton();
        txtTextRC4 = new javax.swing.JTextField();
        txtResultRC4 = new javax.swing.JTextField();
        txtKeyRC4 = new javax.swing.JTextField();
        jPanelHome = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("jLabel2");

        Jpanel_Menu.setBackground(new java.awt.Color(153, 153, 255));
        Jpanel_Menu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        Jpanel_Menu.setMaximumSize(new java.awt.Dimension(143, 463));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("A5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("RC4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel7.setText("Menu");

        Jpanel1.setBackground(new java.awt.Color(255, 51, 51));
        Jpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jpanel1MouseClicked(evt);
            }
        });

        jLabel8.setText("Home");

        javax.swing.GroupLayout Jpanel1Layout = new javax.swing.GroupLayout(Jpanel1);
        Jpanel1.setLayout(Jpanel1Layout);
        Jpanel1Layout.setHorizontalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Jpanel1Layout.setVerticalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        javax.swing.GroupLayout Jpanel_MenuLayout = new javax.swing.GroupLayout(Jpanel_Menu);
        Jpanel_Menu.setLayout(Jpanel_MenuLayout);
        Jpanel_MenuLayout.setHorizontalGroup(
            Jpanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Jpanel_MenuLayout.setVerticalGroup(
            Jpanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addComponent(Jpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        JpanelMain.setBackground(new java.awt.Color(204, 255, 204));
        JpanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));

        jPanelA5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("A5");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Result");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Text");

        btnKeyGenaration.setText("Key_Genaration");
        btnKeyGenaration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeyGenarationMouseClicked(evt);
            }
        });

        ENCRYPTA5.setText("ENCRYPT");
        ENCRYPTA5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENCRYPTA5MouseClicked(evt);
            }
        });

        btnDECRYPTA5.setText("DECRYPT");
        btnDECRYPTA5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDECRYPTA5MouseClicked(evt);
            }
        });

        txtKeyA5.setColumns(20);
        txtKeyA5.setLineWrap(true);
        txtKeyA5.setRows(5);
        jScrollPane2.setViewportView(txtKeyA5);

        javax.swing.GroupLayout jPanelA5Layout = new javax.swing.GroupLayout(jPanelA5);
        jPanelA5.setLayout(jPanelA5Layout);
        jPanelA5Layout.setHorizontalGroup(
            jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelA5Layout.createSequentialGroup()
                .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelA5Layout.createSequentialGroup()
                        .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelA5Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanelA5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnKeyGenaration)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelA5Layout.createSequentialGroup()
                                .addComponent(ENCRYPTA5)
                                .addGap(69, 69, 69)
                                .addComponent(btnDECRYPTA5))
                            .addComponent(txtTextA5, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                            .addComponent(txtResultA5)))
                    .addGroup(jPanelA5Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanelA5Layout.setVerticalGroup(
            jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelA5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTextA5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeyGenaration, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultA5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ENCRYPTA5)
                    .addComponent(btnDECRYPTA5))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jPanelRC4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel9.setText("RC4");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Key");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Text");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Result");

        btnECRYPTRC4.setText("ENCRYPT");
        btnECRYPTRC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnECRYPTRC4MouseClicked(evt);
            }
        });

        btnDECRYPTRC4.setText("DECRYPT");
        btnDECRYPTRC4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDECRYPTRC4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRC4Layout = new javax.swing.GroupLayout(jPanelRC4);
        jPanelRC4.setLayout(jPanelRC4Layout);
        jPanelRC4Layout.setHorizontalGroup(
            jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRC4Layout.createSequentialGroup()
                .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRC4Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtKeyRC4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelRC4Layout.createSequentialGroup()
                                    .addComponent(btnECRYPTRC4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDECRYPTRC4)))
                            .addComponent(txtTextRC4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultRC4)))
                    .addGroup(jPanelRC4Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
        );
        jPanelRC4Layout.setVerticalGroup(
            jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRC4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTextRC4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeyRC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultRC4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanelRC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnECRYPTRC4)
                    .addComponent(btnDECRYPTRC4))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanelHome.setBackground(new java.awt.Color(204, 255, 204));
        jPanelHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));
        jPanelHome.setForeground(new java.awt.Color(204, 255, 204));
        jPanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelHomeMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel13.setText("CẢM ƠN BẠN ĐÃ SỬ DỤNG");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel14.setText("CHƯƠNG TRÌNH NÀY");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Click các nút bên thanh menu để sử dụng chương trình!");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel14))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JpanelMainLayout = new javax.swing.GroupLayout(JpanelMain);
        JpanelMain.setLayout(JpanelMainLayout);
        JpanelMainLayout.setHorizontalGroup(
            JpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelMainLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanelA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(JpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelMainLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanelRC4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(JpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        JpanelMainLayout.setVerticalGroup(
            JpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelA5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(JpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelMainLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanelRC4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
            .addGroup(JpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jpanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(210, 210, 210)
                    .addComponent(jLabel5)
                    .addContainerGap(611, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDECRYPTA5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDECRYPTA5MouseClicked
        // TODO add your handling code here:
         String encryptedText =  txtTextA5.getText();
        if (encryptedText != null && secretKey != null) {
            try {
                String decryptedText = decrypt(encryptedText, secretKey);
                txtResultA5.setText(decryptedText);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Decryption failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui long nhap Key truoc");
        }
        
    }//GEN-LAST:event_btnDECRYPTA5MouseClicked

    private void Jpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jpanel1MouseClicked
        // TODO add your handling code here:
        jPanelA5.setVisible(false);
        jPanelRC4.setVisible(false);
        jPanelHome.setVisible(true);
    }//GEN-LAST:event_Jpanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        jPanelA5.setVisible(true);
        jPanelRC4.setVisible(false);
        jPanelHome.setVisible(false);

    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
         jPanelA5.setVisible(false);
        jPanelRC4.setVisible(true);
         jPanelHome.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void ENCRYPTA5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENCRYPTA5MouseClicked
        String plainText = txtTextA5.getText();
        if (plainText != null && secretKey != null) {
            try {
                String encryptedText = encrypt(plainText, secretKey);
                txtResultA5.setText(encryptedText);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERROR Encryption failed: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui long nhap key truoc");
        }
        
              
             
    }//GEN-LAST:event_ENCRYPTA5MouseClicked

    private void btnKeyGenarationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeyGenarationMouseClicked
        secretKey = generateSecretKey();
        txtKeyA5.setText(secretKey.toString());
        JOptionPane.showMessageDialog(null, "Qua trinh tao key da thanh cong!!!");
    }//GEN-LAST:event_btnKeyGenarationMouseClicked

    private void btnECRYPTRC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnECRYPTRC4MouseClicked
        
            try{
            NewJFrame RC4 = new  NewJFrame(txtKeyRC4.getText());
            String plaintext = txtTextRC4.getText();
            String CipherText= RC4.encryptRC4(plaintext);
            txtResultRC4.setText(CipherText);
        }
        catch (Exception e){
                JOptionPane.showMessageDialog(null, "Vui long nhap key truoc");
            }
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnECRYPTRC4MouseClicked

    private void btnDECRYPTRC4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDECRYPTRC4MouseClicked
        // TODO add your handling code here:
        try{
         NewJFrame RC4 =new NewJFrame(txtKeyRC4.getText());
        String ciphertext =  txtTextRC4.getText();
        String PlainText = RC4.decryptRC4(ciphertext);
         txtResultRC4.setText(PlainText);
        }
        catch (Exception e){
          JOptionPane.showMessageDialog(null, "Vui long nhap key truoc!");
        }
        
    }//GEN-LAST:event_btnDECRYPTRC4MouseClicked

    private void jPanelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHomeMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPanelHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENCRYPTA5;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JPanel JpanelMain;
    private javax.swing.JPanel Jpanel_Menu;
    private javax.swing.JButton btnDECRYPTA5;
    private javax.swing.JButton btnDECRYPTRC4;
    private javax.swing.JButton btnECRYPTRC4;
    private javax.swing.JButton btnKeyGenaration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelA5;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelRC4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtKeyA5;
    private javax.swing.JTextField txtKeyRC4;
    private javax.swing.JTextField txtResultA5;
    private javax.swing.JTextField txtResultRC4;
    private javax.swing.JTextField txtTextA5;
    private javax.swing.JTextField txtTextRC4;
    // End of variables declaration//GEN-END:variables
}
